routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('teachers','TeacherController')->middleware('checkLogin');

Route::resource('students','StudentController')->middleware('checkLogin');

Route::get('/addStudent',['as' => 'students.create','uses' =>'StudentController@create']);


Route::middleware(['checkLogin'])->group(function() {

    Route::resource('teachers', 'TeacherController', [
        'only' => [
            'index', 'store', 'update'
        ]
    ]);

    Route::resource('students', 'StudentController', [
        'only' => [
            'index', 'store', 'update'
        ]
    ]);

});

Route::get('logout', function ()
{
    auth()->logout();
    Session()->flush();

    return Redirect::to('/login');
})->name('logout');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = [
        'name', 'imagename','phone','email'
    ];

    public function students()
    {
        return $this->hasMany(Student::class,'teacher_id','id');
    }
    
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Teacher;
use Illuminate\Http\Request;
use Image;
use Validator;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {        
        $teachers = Teacher::latest()->paginate(5);
  
        return view('teachers.index',compact('teachers'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'imagename' => 'required',
        ]);

        if($request->hasfile('imagename'))
        {
           
            $imagename = $request->file('imagename');
            $filename = time() . '.' . $imagename->getClientOriginalExtension();
            Image::make($imagename)->resize(300, 300)->save( public_path('/uploads/profile_image/' . $filename) );
            if(!$filename)
            {           
                return redirect()->route('teacher.create')->with('error','Please select valid image!');
            }
        }
        $teacher = new Teacher;
        $teacher->name = $request->post('name');
        $teacher->phone = $request->post('phone');
        $teacher->email = $request->post('email');
        $teacher->Description = $request->post('Description');
        $teacher->imagename = isset($filename)?$filename:'default.png';
        // dd($teacher);
        $teacher->save();
        // Teacher::create($request->all());
   
        return redirect()->route('teachers.index')
                        ->with('success','Teacher added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        $students = Teacher::find($teacher->id)->students;
        return view('teachers.show',compact('teacher','students'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit(Teacher $teacher)
    {
        return view('teachers.edit',compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Teacher $teacher)
    {
        $request->validate([
            'name' => 'required',
        ]);
       
        if($request->hasfile('imagename'))
        {
           
            $imagename = $request->file('imagename');
            $filename = time() . '.' . $imagename->getClientOriginalExtension();
            Image::make($imagename)->resize(300, 300)->save( public_path('/uploads/profile_image/' . $filename) );
            if(!$filename)
            {           
                return redirect()->route('teachers.edit')->with('error','Please select valid image!');
            }
        } else
        {
            $filename=$request->post('prev_image');
        }

        $teacher=Teacher::find($teacher->id);
        $teacher->name = $request->post('name');
        $teacher->phone = $request->post('phone');
        $teacher->email = $request->post('email');
        $teacher->Description = $request->post('Description');
        $teacher->imagename = isset($filename)?$filename:'default.png';
        // dd($teacher);
        $teacher->save();

        // $teacher->update($request->all());
  
        return redirect()->route('teachers.index')
                        ->with('success','Teacher updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Teacher $teacher)
    {
        $teacher->students()->delete();
        $teacher->delete();
  
        return redirect()->route('teachers.index')
                        ->with('success','Teacher deleted successfully');
    }
}

resources/views/teachers/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Teacher</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('teachers.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form enctype="multipart/form-data" action="{{ route('teachers.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name <span>*</span></strong>
                <input type="text" required name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone <span>*</span></strong>
                <input type="text" required name="phone" class="form-control" placeholder="Phone">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email <span>*</span></strong>
                <input type="email" required name="email" class="form-control" placeholder="Email">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description</strong>
                <textarea name="Description" class="form-control" placeholder="Description">
                </textarea>
            </div>
        </div>
        <div class="form-group col-md-6">
                <label>Profile Picture <span>*</span></label>                
                
                    <input type="file" name="imagename" class="form-control">
                    <input type="hidden" class="token_value" name="_token" value="{{csrf_token()}}">                  
                
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
</div>

</div>
</div>
</div>

@endsection

resources/views/teachers/edit.blade.php
@extends('layouts.app')
   
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Teacher</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('teachers.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form enctype="multipart/form-data" action="{{ route('teachers.update',$teacher->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name <span>*</span></strong>
                    <input type="text" name="name" required value="{{ $teacher->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone <span>*</span></strong>
                <input type="text" name="phone" required value="{{ $teacher->phone }}" class="form-control" placeholder="Phone">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email <span>*</span></strong>
                <input type="email" name="email" required value="{{ $teacher->email }}" class="form-control" placeholder="Email">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description</strong>
                <textarea name="Description" class="form-control" placeholder="Description">
                {{ $teacher->Description }}
                </textarea>
            </div>
        </div>
            <div class="form-group col-md-6">
                <label>Profile Picture <span>*</span></label>
                <div>
                    <span id="st_message"></span>
                    <img id="profile_pic" src="{{ URL::asset('/uploads/profile_image/'.$teacher->imagename) }}" width=100 height=100/>
                </div>
                
                    <input type="file" name="imagename" class="form-control" >
                    <input type="hidden" class="token_value" name="_token" value="{{csrf_token()}}"> 
                    <input type="hidden" class="" name="prev_image" value="{{ $teacher->imagename }}">                  
                
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
    </div>
    </div>
    </div>
    </div>
@endsection

resources/views/teachers/index.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Teachers</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('teachers.create') }}"> Add New Teacher</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Image</th>
            <th>Description</th>

            <th width="280px">Action</th>
        </tr>
        @foreach ($teachers as $teacher)
        <tr>
            <td><a href="{{ route('teachers.show',$teacher->id) }}">{{ $teacher->name }}</a></td>
            <td>{{ $teacher->phone }}</td>
            <td>{{ $teacher->email }}</td>
            
            <td><img id="profile_pic" src="{{ URL::asset('/uploads/profile_image/'.$teacher->imagename) }}" width=50 height=50/></td>
            <td title="{{ $teacher->Description }}">{{ Str::limit($teacher->Description,50) }}</td>
            <td>
                <form action="{{ route('teachers.destroy',$teacher->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('teachers.show',$teacher->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('teachers.edit',$teacher->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" onclick="return confirm('Are you sure, you want to delete this teacher because all the related students will also be deleted?')" class="btn btn-danger">Delete</button>
                </form>
            </td>
            
        </tr>
        @endforeach
    </table>
  
    {!! $teachers->links() !!}
      </div>
      </div>
      </div>
      </div>
@endsection

resources/views/teachers/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <div class="card detail_div">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Teacher Detail</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('teachers.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                
                <img id="profile_pic" src="{{ URL::asset('/uploads/profile_image/'.$teacher->imagename) }}" width=50 height=50/>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $teacher->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone:</strong>
                {{ $teacher->phone }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $teacher->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $teacher->Description }}
            </div>
        </div>
        
    </div>
    </div>
    <div class="card">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Students List</h2>
            </div>
        </div>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Image</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($students as $student)
        <tr>
            <td>{{ $student->name }}</td>
            <td>{{ $student->phone }}</td>
            <td>{{ $student->email }}</td>
            <td><img id="profile_pic" src="{{ URL::asset('/uploads/profile_image/'.$student->imagename) }}" width=50 height=50/></td>
            <td>
                <form action="{{ route('students.destroy',$student->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('students.show',$student->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('students.edit',$student->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    </div>
    </div>
    </div>
    </div>
@endsection