routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('teachers','TeacherController')->middleware('checkLogin');

Route::resource('students','StudentController')->middleware('checkLogin');

Route::get('/addStudent',['as' => 'students.create','uses' =>'StudentController@create']);


Route::middleware(['checkLogin'])->group(function() {

    Route::resource('teachers', 'TeacherController', [
        'only' => [
            'index', 'store', 'update'
        ]
    ]);

    Route::resource('students', 'StudentController', [
        'only' => [
            'index', 'store', 'update'
        ]
    ]);

});

Route::get('logout', function ()
{
    auth()->logout();
    Session()->flush();

    return Redirect::to('/login');
})->name('logout');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'name', 'imagename','phone','email'
    ];
    
    public function teacher()
    {
        return $this->belongsTo(Teacher::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use App\Teacher;
use Illuminate\Http\Request;
use Image;
use Validator;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = Teacher::pluck('name', 'id');
        $students = Student::latest()->paginate(5);
        // dd($students);
        return view('students.index',compact('students','teachers'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $teachers = Teacher::pluck('name', 'id');
        return view('students.create',compact('teachers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:50',
            'imagename' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            'teacher_id' => 'required|numeric',
            'phone' => 'required|digits:10',
            'email' => 'required|email',
        ],
        [
            'imagename.required' => 'Profile picture should not be empty',
            'imagename.image' => 'Profile picture must be a file of type: jpeg, png, jpg.',
        ]
        );

        if($request->hasfile('imagename'))
        {
           
            $imagename = $request->file('imagename');
            $filename = time() . '.' . $imagename->getClientOriginalExtension();
            Image::make($imagename)->resize(300, 300)->save( public_path('/uploads/profile_image/' . $filename) );
            if(!$filename)
            {           
                return redirect()->route('student.create')->with('error','Please select valid image!');
            }
        }
        $student = new Student;
        $student->name = $request->post('name');
        $student->teacher_id = $request->post('teacher_id');
        $student->phone = $request->post('phone');
        $student->email = $request->post('email');
        $student->imagename = isset($filename)?$filename:'default.png';
        // dd($student);
        $student->save();
   
        return redirect()->route('students.index')
                        ->with('success','Student added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return view('students.show',compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        $teachers = Teacher::pluck('name', 'id');
        $selectedID = $student->teacher_id;
        return view('students.edit',compact('student','teachers','selectedID'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        // dd($student->id);
        $request->validate([
            'name' => 'required|max:50',
            'imagename' => 'image|mimes:jpeg,png,jpg|max:2048',
            'teacher_id' => 'required|numeric',
            'phone' => 'required|digits:10',
            'email' => 'required|email',
        ]);
            
        if($request->hasfile('imagename'))
        {
           
            $imagename = $request->file('imagename');
            $filename = time() . '.' . $imagename->getClientOriginalExtension();
            Image::make($imagename)->resize(300, 300)->save( public_path('/uploads/profile_image/' . $filename) );
            if(!$filename)
            {           
                return redirect()->route('students.edit')->with('error','Please select valid image!');
            }
        }else
        {
            $filename=$request->post('prev_image');
        }

        $stu = Student::find($student->id);
        $stu->name = $request->post('name');
        $stu->teacher_id = $request->post('teacher_id');
        $stu->phone = $request->post('phone');
        $stu->email = $request->post('email');
        $stu->imagename = isset($filename)?$filename:'default.png';
        if($stu->save()){
            return redirect()->route('students.index')
                        ->with('success','Student updated successfully');
        } else {
            return redirect()->route('students.index')
                        ->with('error','Student is not updated');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
  
        return redirect()->route('students.index')
                        ->with('success','Student deleted successfully');
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Student</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form enctype="multipart/form-data" action="{{ route('students.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name <span>*</span></strong>
                <input type="text" name="name" required class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone <span>*</span></strong>
                <input type="text" name="phone" required class="form-control" placeholder="Phone">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email <span>*</span></strong>
                <input type="email" name="email" required class="form-control" placeholder="Email">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Teacher <span>*</span></strong>
                <select class="form-control" name="teacher_id">
                    <option>Select Teacher</option>
                    @foreach ($teachers as $key => $value)
                        <option value="{{ $key }}"> 
                            {{ $value }} 
                        </option>
                    @endforeach    
                </select>
            </div>
        </div>
        
        <div class="form-group col-md-6">
                <label>Profile Picture <span>*</span></label>             
                
                    <input type="file" name="imagename" class="form-control">
                    <input type="hidden" class="token_value" name="_token" value="{{csrf_token()}}">                  
                
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
</div>

</div>
</div>
</div>

@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')
   
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Student</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form enctype="multipart/form-data" action="{{ route('students.update',$student->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name <span>*</span></strong>
                    <input type="text" name="name" required value="{{ $student->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Phone <span>*</span></strong>
                    <input type="text" name="phone" required value="{{ $student->phone }}" class="form-control" placeholder="Phone">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email <span>*</span></strong>
                    <input type="email" name="email" required value="{{ $student->email }}" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Teacher <span>*</span></strong>
                <select class="form-control" name="teacher_id">
                    <option>Select Teacher</option>
                    @foreach ($teachers as $key => $value)
                        <option value="{{ $key }}" {{ ( $key == $selectedID) ? 'selected' : '' }}> 
                            {{ $value }} 
                        </option>
                    @endforeach    
                </select>
            </div>
        </div>
            <div class="form-group col-md-6">
                <label>Profile Picture <span>*</span></label>
                <div>
                    <span id="st_message"></span>
                    <img id="profile_pic" src="{{ URL::asset('/uploads/profile_image/'.$student->imagename) }}" width=100 height=100/>
                   
                </div>
                
                    <input type="file" name="imagename" class="form-control">
                    <input type="hidden" class="token_value" name="_token" value="{{csrf_token()}}">                  
                    <input type="hidden" class="" name="prev_image" value="{{ $student->imagename }}">   
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
    </div>
    </div>
    </div>
    </div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Students</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('students.create') }}"> Add New Student</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Teacher</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Image</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($students as $student)
        <tr>
            <td>{{ $student->name }}</td>
            <td>{{ $teachers[$student->teacher_id] }}</td>
            <td>{{ $student->phone }}</td>
            <td>{{ $student->email }}</td>
            <td><img id="profile_pic" src="{{ URL::asset('/uploads/profile_image/'.$student->imagename) }}" width=50 height=50/></td>
            <td>
                <form action="{{ route('students.destroy',$student->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('students.show',$student->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('students.edit',$student->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" onclick="return confirm('Are you sure, you want to delete this student?')"  class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $students->links() !!}
      </div>
      </div>
      </div>
      </div>
@endsection

resources/views/students/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Student Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                
                <img id="profile_pic" src="{{ URL::asset('/uploads/profile_image/'.$student->imagename) }}" width=50 height=50/>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $student->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone:</strong>
                {{ $student->phone }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $student->email }}
            </div>
        </div>
       
    </div>
    </div>
    </div>
    </div>
    </div>
@endsection